#
# Makefile for the fingerprint drivers.
#

# Each configuration option enables a list of files.
#ccflags-y += -Idrivers/misc/

#ifeq ($(CONFIG_INPUT_IX_BTP),y)
#obj-$(CONFIG_INPUT_IX_BTP)	+= ix_btp_tee.o
#endif
obj-y += ix_btp.o
