#drivers/input/touchscreen/focaltech_touch/focaltech_test
#
#Makefile for test module
#
	
	obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_test.o
	obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_test_main.o
	obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_test_ini.o
	obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_test_global.o
	obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_test_detail_threshold.o	
#	obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_ALL) += focaltech_test_config_ft3c47.o
#	obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_ALL) += focaltech_test_ft3c47.o
#	obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_ALL) += focaltech_test_config_ft5x46.o
#	obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_ALL) += focaltech_test_ft5x46.o
#	obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_ALL) += focaltech_test_config_ft6x36.o
#	obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_ALL) += focaltech_test_ft6x36.o
#	obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_ALL) += focaltech_test_config_ft5822.o
#	obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_ALL) += focaltech_test_ft5822.o
#	obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_ALL) += focaltech_test_config_ft8606.o
#	obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_ALL) += focaltech_test_ft8606.o
	obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_test_config_ft8716.o
	obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_test_ft8716.o
#	obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_ALL) += focaltech_test_config_ft8736.o
#	obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_ALL) += focaltech_test_ft8736.o
#	obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_ALL) += focaltech_test_config_ft8607.o	
#	obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_ALL) += focaltech_test_ft8607.o
#	obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_ALL) += focaltech_test_config_ftE716.o
#	obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_ALL) += focaltech_test_ftE716.o
#	obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_ALL) += focaltech_test_config_ftE736.o
#	obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_ALL) += focaltech_test_ftE736.o
